Master
sveltejs/svelte-devtools pull request #70
Opened 2022-03-17 10:54 UTC by crossjs

2022-03-24 17:43 UTC, brandonbloom commented
Just wanted to confirm: I build/installed this change locally and it does indeed fix the issue. Thanks!

2022-03-31 12:45 UTC, HoffmannP commented
Works for me two, please merge

2022-04-01 08:06 UTC, Little-Star-Star commented
It works good for me in v99 of chrome.

2022-04-05 04:47 UTC, c19 commented
the pr version works for me in v100.0.4896.60 of chrome, macos

2022-04-19 22:28 UTC, jefflafay commented
This works on my macos with chrome 100.0.4896.88  (x86_64). The production chrome plugin is still broken without this PR.

2022-04-26 03:14 UTC, ianyxtan commented
This fix didn't work for me. Used firefox at the mean time.

2022-05-30 04:28 UTC, GM-David commented
Nice 👍

2022-08-30 12:14 UTC, mgrubinger commented
Are there any plans to merge this PR?

2022-08-30 12:23 UTC, bershanskiy commented
> Are there any plans to merge this PR?

Not that I know of. This repository appears to be abandoned (last commit in June 2021). If you like to, you can build extension locally or even just open the `ChromeData` folder and patch it manually.

2022-09-08 20:55 UTC, rocketinventor approved these changes
Fixes the issue! Awesome!

2022-09-15 21:25 UTC, bershanskiy commented
Relevant Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1364293

2022-09-22 21:18 UTC, Saibamen requested changes

2022-09-22 21:18 UTC, Saibamen commented on src/background.js
> +  if (port.sender.url.replace('//devtools', '/devtools') == chrome.runtime.getURL('/devtools/panel.html')) {
```suggestion
  if (port.sender.url.replaceAll('//', '/') == chrome.runtime.getURL('/devtools/panel.html')) {
```

And what do you think about adding `toLowerCase()`?

2022-10-14 17:13 UTC, bershanskiy commented
The Chromium DevTools bug (linked above) was fixed and fix was already rolled into Chromium. I tested on Chromium Version 108.0.5358.0 (Developer Build) (64-bit) and `sender.url` was fine. Most likely, Chromium Canary was already fixed too. We can expect Chromium 108 to release with Svelte DevTools working again.

2022-10-29 18:02 UTC, bershanskiy commented
I just checked on Google Chrome Beta 108 and Svelte Devtools worked fine. If you still would like to use this extension, you can just install Chrome Beta or wait until November 29 for Chrome 108 to be released officially.

Test details:
 - Svelte Devtools 1.3.0 installed from CWS
 - Google Chrome Beta 108.0.5359.22
 - macOS Montrey 12.6 on MacBook Pro (Retina, 13-inch, Early 2015)

2023-09-14 09:43 UTC, closed without merging